backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "uniformes"
    label: "Uniformes"
    folder: "public/images/uniformes"
    create: true
    media_folder: ""
    public_folder: ""
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Nombre", name: "title", widget: "string", required: false }
      - { label: "Descripci贸n", name: "description", widget: "text", required: false }

  - name: "estampados"
    label: "Estampados"
    folder: "public/images/estampados"
    create: true
    media_folder: ""
    public_folder: ""
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Nombre", name: "title", widget: "string", required: false }
      - { label: "Descripci贸n", name: "description", widget: "text", required: false }

  - name: "gorras"
    label: "Gorras"
    folder: "public/images/gorras"
    create: true
    media_folder: ""
    public_folder: ""
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Nombre", name: "title", widget: "string", required: false }
      - { label: "Descripci贸n", name: "description", widget: "text", required: false }

  - name: "vasos"
    label: "Vasos"
    folder: "public/images/vasos"
    create: true
    media_folder: ""
    public_folder: ""
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Nombre", name: "title", widget: "string", required: false }
      - { label: "Descripci贸n", name: "description", widget: "text", required: false }
