backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "uniformes"
    label: "Uniformes"
    label_singular: "Uniforme"
    folder: "public/images/uniformes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Título", name: "title", widget: "string", default: "Uniforme"}
      - {label: "Fecha", name: "date", widget: "datetime", default: ""}

  - name: "gorras"
    label: "Gorras"
    label_singular: "Gorra"
    folder: "public/images/gorras"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Título", name: "title", widget: "string", default: "Gorra"}
      - {label: "Fecha", name: "date", widget: "datetime", default: ""}

  - name: "vasos"
    label: "Vasos"
    label_singular: "Vaso"
    folder: "public/images/vasos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Título", name: "title", widget: "string", default: "Vaso"}
      - {label: "Fecha", name: "date", widget: "datetime", default: ""}

  - name: "estampados"
    label: "Estampados"
    label_singular: "Estampado"
    folder: "public/images/estampados"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Título", name: "title", widget: "string", default: "Estampado"}
      - {label: "Fecha", name: "date", widget: "datetime", default: ""}
